"""
A Collatz sequence is generated by repeatedly applying the following rules to an integer and then to each resulting integer in turn:

If even: divide by 2.
If odd: multiply by 3, then add 1.
The Collatz algorithm has been tested and found to always reach 1 for all positive integers.

Create a function that, when given two positive integers a b, returns the string "a" if integer a took fewer steps to reach 1 than b when passed through the Collatz sequence, or "b" if integer b took fewer steps to reach 1 than a.
"""
counting = 0
collatzval = -1

def collatz(a):
    global counting
    global collatzval
    if(a!=1):
        if(a%2):
            a=a*3+1            
        else:
            a=a/2

        counting+=1
        collatz(a)
    else:
        collatzval = counting
        counting =0


def function(a, b):
    #a and b are ints
    global collatzval
    collatz(a)
    a_collatz = collatzval
    collatz(b)
    b_collatz = collatzval

    if(a_collatz>b_collatz):
        print("a")
    elif(b_collatz>a_collatz):
        print("b")
    else:
        print("a and b are the same")

function(950,15)
